# Generated by Django 3.1.3 on 2020-11-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileurl',
            field=models.CharField(default='https://placekitten.com/300/300', max_length=200),
        ),
    ]
