# Generated by Django 3.1.3 on 2020-11-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profileurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileurl',
            field=models.CharField(max_length=200),
        ),
    ]
